# Generated by Django 4.0.4 on 2022-04-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('hkuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VenueRecord',
            fields=[
                ('venue_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=2)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=2)),
                ('hkuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studysafe_core.memberrecord')),
                ('venue_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studysafe_core.venuerecord')),
            ],
        ),
    ]
