# Generated by Django 4.0.3 on 2022-04-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberRecords',
            new_name='MemberRecord',
        ),
    ]
